overrides:
  - files: '**/*.ts'
    plugins:
      - prettier
      - '@typescript-eslint'
    extends:
      - prettier
      - plugin:import/errors
      - plugin:import/warnings
      - plugin:import/typescript
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    rules:
      '@typescript-eslint/no-unsafe-argument': warn
      '@typescript-eslint/no-unsafe-member-access': warn
      '@typescript-eslint/no-unsafe-call': warn
      '@typescript-eslint/no-unsafe-assignment': warn
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/no-unsafe-return': warn
